media: microchip-sama5d2-isc: fix CBC_ENABLE reference after rename
Complete the CBC_ENABLE to CBHS_ENABLE rename that was missed in the
microchip-sama5d2-isc driver

error: 'CBC_ENABLE' undeclared (first use in this function)

Fixes: 588539b9bb2b ("media: microchip-isc: Rename CBC to CBHS")
Signed-off-by: Balakrishnan Sambath <balakrishnan.s@microchip.com>