media: microchip: fix an unused-but-set warning
Clang allmodconfig builds report:
../drivers/media/platform/microchip/microchip-vcpp.c:788:25: error: variable 'mchp_vcpp' set but not used [-Werror,-Wunused-but-set-variable]
        struct mchp_vcpp_fpga *mchp_vcpp;

Drop the variable, and cull the unneeded switch statement in the
process.

Signed-off-by: Conor Dooley <conor.dooley@microchip.com>